name: Setup Directory Structure

on:
  workflow_dispatch:   # manual run only (SAFE)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create folders and placeholders
        run: |
          mkdir -p setup bin assets/icons assets/configs assets/wallpapers burp

          touch install.sh README.md LICENSE .gitignore

          touch setup/01-ubuntu.sh \
                setup/02-xfce-minimal.sh \
                setup/03-vnc.sh \
                setup/04-java.sh \
                setup/05-burp.sh \
                setup/06-desktop.sh \
                setup/07-aliases.sh

          touch bin/burp bin/startdesk bin/stopdesk

          echo "burp/" >> .gitignore
          echo "# BurpDroid" > README.md

      - name: Commit files
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          git add .

          git diff --cached --quiet && exit 0 || git commit -m "Initial directory structure"

          git push
